# magento docker

version: '3'
networks:
    default:
        external:
           name: magento
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./etc/nginx/certs:/etc/nginx/certs:ro
          - ./etc/nginx/conf.d:/etc/nginx/conf.d
          - ./etc/nginx/vhost.d:/etc/nginx/vhost.d 
          - ./etc/nginx/html:/usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro
    php7.2:
        container_name: php7.2
        user: www-data
        image: magento/php7.2
        build:
            context: ./etc/php
            dockerfile: Dockerfile7.2
        command: echo "Build only, not started by default."
    php7.1:
        container_name: php7.1
        user: www-data
        image: magento/php7.1
        build:
            context: ./etc/php
            dockerfile: Dockerfile7.1
        command: echo "Build only, not started by default."
    php7.0:
        container_name: php7.0
        user: www-data
        image: magento/php7.0
        build:
            context: ./etc/php
            dockerfile: Dockerfile7.0
        command: echo "Build only, not started by default."
    mysqldb:
        image: mysql:5.7.22
        container_name: mysqldb
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=mysql
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - TZ=America/New_York
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mysql/conf.d:/etc/mysql/conf.d"
    redis:
        image: redis:4.0.11
        container_name: redis
        restart: always
        ports:
          - "16379:6379"
        volumes:
            - "./etc/redis/redis.conf:/usr/local/etc/redis.conf"
    redis_fpc:
        image: redis:4.0.11
        container_name: redis_fpc
        restart: always
        ports:
          - "16380:6379"
        volumes:
            - "./etc/redis/redis_fpc.conf:/usr/local/etc/redis.conf"
    redis_session:
        image: redis:4.0.11
        container_name: redis_session
        restart: always
        ports:
          - "16381:6379"
        volumes:
            - "./etc/redis/redis_session.conf:/usr/local/etc/redis.conf"
    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
          - "1025:1025"
          - "8025:8025"
    elasticsearch2:
        image: blacktop/elasticsearch:2.4
        container_name: es2
        environment:
          - node.name=es2
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - "./data/es/es2:/usr/share/elasticsearch/data"
          - "./etc/elasticsearch/config/elasticsearch2.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
        ports:
          - 9200:9200
    elasticsearch6:
        image: blacktop/elasticsearch:6.8
        container_name: es6
        environment:
          - node.name=es6
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - "./data/es/es6:/usr/share/elasticsearch/data"
          - "./etc/elasticsearch/config/elasticsearch6.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
        ports:
          - 19200:9200
    rabbitmq:
        environment:
          - RABBITMQ_ERLANG_COOKIE=secret_cookie
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
        container_name: rabbitmq
        hostname: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
          - 15672:15672
          - 5672:5672
        tty: true
        volumes:
          - ./data/rabbitmq:/var/lib/rabbitmq
          - ./etc/rabbitmq/conf:/etc/rabbitmq/
        command:  bash -c "sleep 10; rabbitmq-server; rabbitmq-plugins enable rabbitmq_management;"
