# magento docker

version: '3'
networks:
    default:
        external:
           name: magento
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./etc/nginx/certs:/etc/nginx/certs:ro
          - ./etc/nginx/conf.d:/etc/nginx/conf.d
          - ./etc/nginx/vhost.d:/etc/nginx/vhost.d 
          - ./etc/nginx/html:/usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro
    php:
        container_name: php
        user: www-data
        build:
            context: ./etc/php
            dockerfile: Dockerfile
    php7.1:
        container_name: php7.1
        user: www-data
        build:
            context: ./etc/php
            dockerfile: Dockerfile7.1
    mysqldb:
        image: mysql:5.7.22
        container_name: mysqldb
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=mysql
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - TZ=America/New_York
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mysql/conf.d:/etc/mysql/conf.d"
    redis:
        image: redis:4.0.11
        container_name: redis
        restart: always
        ports:
          - "16379:6379"
        volumes:
            - "./etc/redis/redis.conf:/usr/local/etc/redis.conf"
    redis_fpc:
        image: redis:4.0.11
        container_name: redis_fpc
        restart: always
        ports:
          - "16380:6379"
        volumes:
            - "./etc/redis/redis_fpc.conf:/usr/local/etc/redis.conf"
    redis_session:
        image: redis:4.0.11
        container_name: redis_session
        restart: always
        ports:
          - "16381:6379"
        volumes:
            - "./etc/redis/redis_session.conf:/usr/local/etc/redis.conf"
volumes:
    etc:
