FROM opensearchproject/opensearch:latest

# RUN /usr/share/opensearch/bin/opensearch-plugin remove analysis-icu 
 
# RUN /usr/share/opensearch/bin/opensearch-plugin remove analysis-phonetic

RUN /usr/share/opensearch/bin/opensearch-plugin install analysis-icu 
 
RUN /usr/share/opensearch/bin/opensearch-plugin install analysis-phonetic
